### ISSUE TITLE
Error when loading mesh 

### ISSUE THREAD

**Issue by florian02100** [OGRECave/ogre-next#152]
Hello everyone,

I work on project to load mesh from assimp to ogre 2.2. 

I retrieve vertices and indices and i load it into Mesh V1. 

i've problem when i load the mesh V1 (Mesh->load()) return a crash without error code. I have no error in my console and have no error in ogre log. 

And i can see that sharedVertexData from Mesh is an array of VertexData. The sharedVertexData is build like that :

 **VertexData [numVertexPass]**

What is "numVertexPas" i can change it ? (for me it's 2).

Have you any ideas ? 

Thank you

**Comment by darksylinc** [comment]
Hi!

The information is too vague to be able to help you.

- How are you converting the mesh?
- Can you provide a callstack?
- What's the value of the local variables at the time of crash?

> VertexData [numVertexPass]
> What is "numVertexPas" i can change it ? (for me it's 2).

Ogre wants two copies of the vertex buffer: One used for regular rendering (VpNormal), another to be used during the shadow map caster pass (VpShadow).

The latter should only contain position and can be much thinner because it doesn't need to duplicate vertices caused by normal or UV discontinuities.

However it's not necessary to duplicate the data: if VRAM budget is tight (or there is not much performance to gain) one can do sharedVertexData[VpShadow] = sharedVertexData[VpNormal]; and Ogre will automatically only delete sharedVertexData[VpNormal] on shutdown (rather than try to delete both pointers).

Mesh::prepareForShadowMapping can be used to automatically generate an optimized VpShadow version based on VpNormal.
