### ISSUE TITLE
Towards an API/ABI stability

### ISSUE THREAD

**Issue by j-rivero** [OGRECave/ogre-next#258]
As part of #232 , it would be great for the distribution of OGRE-Next to be able to maintain at least a minimum policy about not breaking ABI/API on every single version bump. As an example of this, this bug for [Debian packagers of ogre-1.12 ](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=989344#71)could serve to understand well the level of effort that needs to be done when no policy is in place.

Note that OGRE project has moved itself to[ Semantic Versioning starting in version 13](https://www.ogre3d.org/2021/08/14/ogre-13-released). It is not that I'm proposing to jump directly to Semantic Versioning but at least have a minimal policy in place. Maybe starting with respecting ABI/API in bumping the patch number in version is a good start.

It was mentioned in https://github.com/OGRECave/ogre-next/issues/232#issuecomment-939187318 that there are many CMake flags that will break ABI. I think that this is perfectly fine and does not need to be modified, distribution of software downstream (Linux distribution, conda-forge, etc.) should take this into account. To clarify things, we expect API/ABI stability in bumping versions when using **the same set of flags**. Any change in the compilation flags that breaks ABI/API should be handled by packagers depending on the procedures of the distribution, not a problem for the OGRE-Next project here.

**Comment by darksylinc** [comment]
I [added `generateAbiCookie`](https://github.com/OGRECave/ogre-next/commit/80d7b98a0ed338a23255bfe2e8100b306929f81b) which is optional for Root and [mandatory for Plugins](https://github.com/OGRECave/ogre-next/commit/f9139d429c7f845c032b4db93dbe72f040b25841).

This will solve a long time ABI issue where users could mix older/newer DLLs\*; or they would point to the wrong OgreBuildSettings.h (or there's multiple versions of the shared libs installed and the wrong header/lib combo was picked up)

\* By DLLs I also mean Linux shared objects.

This is a step forward towards ABI stability. The point of this check is that the wrong DLLs aren't loaded, and that CMake flags are consistent.

**Comment by darksylinc** [comment]
OK I just pushed https://github.com/OGRECave/ogre-next/commit/74e2d30130727edcafc09a53cf3d99cded368d0d which will need more testing but basically should perform the following (for branches >= 2.4, non-master):

 - Compile Ogre on Ubuntu (this was already happening as per our CI)
 - Run abi-dumper on all the *.so results
 - Download a base dump from Github (none is currently uploaded, since 2.4 branch isn't frozen yet)
 - Compare the build against the base and generate reports; marking a non-zero exit code if one fails
 - Generate a report

This should help us identify ABI breakage, the same way we do in Ignition

**Comment by darksylinc** [comment]
OK some strides have been made in this regard:

 - ABI function to prevent ABI-incompatible builds (i.e. wrong versions, wrong CMake options) from being mixed
 - CI setup so that ABI stability is checked

## What is missing:

 - [ ] Perform tests with ABI checker to see how easily Ogre breaks. The main problem is that ABI stability in OgreNext is very hard. Private variables are not hidden from users. This may be possible if we stick to freezing patch version very strictly. This will heavily affect my ability to patch or fix Ogre bugs that affect Ignition though
 - [ ] José's [patch](https://github.com/OGRECave/ogre-next/issues/259#issuecomment-1027999871) for renaming all libs `libOgreSomething.so` -> `libOgreNextSomething.so`. This patch is too much of a breaking change. I'm reluctant to add it.
     - It may be possible if we replace it with a variable e.g. Ogre${NEW_NAME}HlmsPbs
     - By default NEW_NAME won't be set in 2.4 (Debian packaging can set NEW_NAME to Next though)
     - In Ogre 2.5, NEW_NAME defaults to NEW_NAME
     - At some point, NEW_NAME is removed and everything becomes OgreNextHlmsPbs and so on.
 - [ ] Change OGRE_SONAME so that patch version is excluded.

**Comment by j-rivero** [comment]
> * 
> 
> *

Thanks so much Matias for moving forward this, appreciated. The approach of introducing the new names using a migration mechanism that can be customized to help Debian maintenance seems a good way forward to me and should make Debian maintenance easier.

**Comment by darksylinc** [comment]
I forgot to mention [this push](https://github.com/OGRECave/ogre-next/commit/100db3dccc393dba48fae08dc2ea191015cf4195) which fixes in a much better way what you had to do [in your forks](https://github.com/ignition-forks/ogre-2.2-release/commit/c60bba9994d2b7ec00454fadf41032328d7ea067).

The default 'auto' will work as you expect (in Ignition) if make or ninja is used.

**Comment by j-rivero** [comment]
Proposal for new API/ABI policy is being discussed in https://github.com/OGRECave/ogre-next/issues/259#issuecomment-1086954560

**Comment by darksylinc** [comment]
SONAME has been updated to only be MAJOR.MINOR instead of MAJOR.MINOR.PATCH.

Do we have anything left? Because it looks like this ticket can be closed.

Same goes for #259

**Comment by j-rivero** [comment]
Happy to close i, thanks @darksylinc .
