### ISSUE TITLE
why still many old code[v1] in this branch?

### ISSUE THREAD

**Issue by RPG3D** [OGRECave/ogre-next#26]
from you blog I know that 1.x keep compatibility， 2.x aims at edge tech；why not make ogre2 more purely? full 2.x， no v1

**Comment by darksylinc** [comment]
Hi!

We have several reasons and that depends on the exact module:

1. v1 Entity:
    - Compatibility with older meshes
    - Ease porting from <= 2.0
    - Morph animations had only been recently added to Items and hasn't yet been ported to 2.2
    - [As explained in the manual](https://ogrecave.github.io/ogre/api/2.1/azdo.html) v2 skeletons turned out very fast but hard to setup and edit, hence editing v1 skeletons is much easier
2. Particle Systems (and Billboards, Ribbon Trails): We haven't written a capable v2 replacement yet.
3. Overlays: Same as Particle Systems. [ColibriGui](https://github.com/darksylinc/colibrigui) was started as a full-featured GUI system and while it's very robust (for _my_ uses) I haven't got the time to fully focus on polishing the details needed to make it replace the overlays
4. HardwareVertex/IndexBuffers: They're still needed by the previously mentioned components
5. The more obscure HardwarePixel/Uniform/Occlusion buffers: You're completely right. They can and should be removed. It's just nobody did it. PRs are welcomed.

Ogre 2.2 specific:
1. All the older interfaces (Texture, PixelFormat, TextureManage) are planned to be removed. Some stuff is inadvertently still in use (e.g. TexBufferPacked uses PixelFormat instead of PixelFormatGpu) but should be easy to port to.
The plan is to move their files to a "Deprecated" subfolder so that users can port from 2.1 to 2.2 without having to deal with broken #include all over their codebase by adding the Deprecated folder to their included directories.
This way users porting their codebase can focus on compiler errors caused by API breakage (e.g. 'function wants a TextureGpu* instead of TexturePtr') instead of focusing on tedious file management.
And eventually remove this folder altogether (i.e. by Ogre 2.3).
I haven't got the time to execute this plan yet.

**Comment by RPG3D** [comment]
thanks for your explanation
