### ISSUE TITLE
fixed function pipeline in 3.0

### ISSUE THREAD

**Issue by rpaciorek** [OGRECave/ogre-next#266]
Hi,

If I am not mistaken then Ogre-next do not support fixed pipeline at all. But sill some code / docs referrer to fixed pipeline. For example `TexCoordModifierControllerValue` (and used by it functions in `TextureUnitState`), for which is working replacement (`TextureAnimationControllerValue`).

Maybe they should be removed? Or (if they are still useful) worth to put note in docs? Because for example `TexCoordModifierControllerValue` vs `TextureAnimationControllerValue` can be confused.

**Comment by darksylinc** [comment]
Hi!

>  Ogre-next do not support fixed pipeline at all

That's correct.

> Some code / docs referrer to fixed pipeline

Actually `TexCoordModifierControllerValue` does work with shaders. The low level material can access the rotation matrix (which is what `TexCoordModifierControllerValue` sets) via `param_named_auto texture_matrix` like they did in 1.x

In 1.x there was also the option of not using shaders and the rotation matrix would work. In Ogre-Next there's no such option

As for `TextureAnimationControllerValue`, that one works specifically for HlmsUnlit (which allows to get non-lit shaders automatically generated for you) and does the same job, just for a different system.

Unlit is preferred for most scenarios; as it handles everything for you (no need to know about shaders) and handles it efficiently.

Low level materials are now only useful for a few select cases (i.e. custom geometry requiring custom shaders) and postprocessing effects (where the material interface is quite user friendly for that). So chances are they'll almost never want to use `TexCoordModifierControllerValue`.
So far the ones that use low level materials the most are large codebases which still haven't ported everything to 2.1+ (since their old shaders in low level materials still work)

But it's still useful, and still supported.

**Comment by rpaciorek** [comment]
Thanks for the clarification.

So maybe [TextureUnitState](https://ogrecave.github.io/ogre-next/api/latest/class_ogre_1_1_texture_unit_state.html) docs should mention about low level material instead of fixed function pipeline? And maybe add some info to [TextureAnimationControllerValue](https://ogrecave.github.io/ogre-next/api/latest/class_ogre_1_1_texture_animation_controller_value.html#details) docs too?
