### ISSUE TITLE
Create Ogre::Root crash when building debug exe with msvc compiler

### ISSUE THREAD

**Issue by maz-1** [OGRECave/ogre-next#269]
#### System Information
- Ogre Version: master
- Operating System / Platform: windows 10
- RenderSystem: opengl
- GPU: gtx1080ti

#### Detailled description
I am using `make_unique<Ogre::Root>("", "ogre.cfg", "ogre.log", "Qt5Ogre23");` to create ogre root while initializing.
It works under release build, but crashed before any window show up in debug build
The debug build flag is `/MDd`

#### Ogre.log
no log

#### Callstack
![3](https://user-images.githubusercontent.com/5277060/156308511-a6c66b8b-7ac5-4bf3-8761-e19634ce4999.PNG)
![1](https://user-images.githubusercontent.com/5277060/156308517-6f1b2167-5d3a-4e8b-b601-e660c6534c4b.PNG)
![2](https://user-images.githubusercontent.com/5277060/156308520-aa037a18-2e66-47b7-85ca-864d727f2c93.PNG)

**Comment by darksylinc** [comment]
Hi! Usually this is caused by

- Different compiler parameters like
- NDEBUG
- DEBUG or _DEBUG absent (which results in different OGRE_DEBUG_LEVEL)
- Different CRT
- Different _ITERATOR_DEBUG_LEVEL
- Wrong OgreBuildSettings.h (i.e. you're using the one for Release)
- *.lib or *.dll mismatch (i.e. it's not the latest version)
- Wrong C++ standard version

Additionally, does it happen if you use new Root() instead of make_unique?

**Comment by maz-1** [comment]
Both ogre-next and my project is built with /MDd
OgreBuildSettings.h are the same for release and debug build
Build both ogre-next and my project from scratch and still crash
use OGRE_NEW Ogre::Root still crash

**Comment by darksylinc** [comment]
The definition of `std::string` depends on C++ version, so yes; it's possible it _may_ cause issues.
