### ISSUE TITLE
Compile error!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [OGRECave/ogre-next#276]
/home/zhangfq/ogre-next/Samples/2.0/Tutorials/Tutorial_Terrain/src/Terra/Terra.cpp:103:66: error: invalid use of incomplete type ‘class Ogre::HlmsDatablock’
  103 |             HlmsTerra *hlms = static_cast<HlmsTerra *>( datablock->getCreator() );

**Comment by darksylinc** [comment]
Hi!

Could you provide more info? I can't repro the problem.

What Ogre version? OS? Compiler? How are you compiling the sample?
These questions are part of the [Bug Report template](https://github.com/OGRECave/ogre-next/issues/new?assignees=&labels=&template=bug_report.md&title=). Please adhere to it.

Otherwise I'll close the ticket.
