### ISSUE TITLE
Normals not handled correctly for non-uniform scaling

### ISSUE THREAD

**Issue by jwwalker** [OGRECave/ogre-next#373]
#### System Information
- Ogre Version: master branch [0a6cd24a91]
- Operating System / Platform: macOS 13.3.1
- RenderSystem: Metal
- GPU: AMD Radeon Pro 560X

#### Detailed description
When the model-view transformation includes a non-uniform scale, the correct way to handle normal vectors is to multiply by the inverse transpose of the upper left 3x3 part of the model-view matrix.  As far as I can tell, this is not what happens in Ogre.  In `800.VertexShader_piece_ps.any`, I see the line

```
@property( hlms_normal || hlms_qtangent )	outVs.normal	= mul( @insertpiece(local_normal), toMidf3x3( worldViewMat ) );@end
```

which seems to be just multiplying the local normal by the 3x3 part of the model-view matrix.

A visual illustration:  First, an unscaled cylinder using lit PBS shading.
![shot_00002 - Scene 1, Shot 2  unscaled, Ogre](https://user-images.githubusercontent.com/730426/233502261-55e7339f-42a7-4982-ba74-09be536f9d0e.jpg)

Here's what it looks like when the cylinder is stretched in the horizontal direction perpendicular to the camera's viewing direction:
![shot_00004 - Scene 1, Shot 4  scaled, Ogre](https://user-images.githubusercontent.com/730426/233502450-967a7114-d119-4a3d-8b7f-0b27dd1e6f47.jpg)
(Notice that the specular highlight is basically unchanged, in spite of the surface being flatter there.)

And here is what I think it ought to look like, as rendered by a different rendering engine:
![shot_00003 - Scene 1, Shot 3  stretched, classic](https://user-images.githubusercontent.com/730426/233502561-aa3ba877-e271-4ff5-a05e-686b666b6ab9.jpg)

**Comment by darksylinc** [comment]
There's discussion here: https://forums.ogre3d.org/viewtopic.php?t=96656

Most people would like to simply ignore this problem due to the performance implications.

But for those who want correctness, the suggested:

```
@property( accurate_non_uniform_scaled_normals )
   normalMat = transpose( inverse( worldMat ) );
@end
```

Could be a good solution (note: IIRC Metal and HLSL don't implement `inverse()` as an intrinsic since it's expensive).

**Comment by jwwalker** [comment]
@darksylinc OK, I looked at the forum thread, but I don't quite understand why it's such a big deal for performance, since the 3x3 normal matrix does not need to be computed and sent to shaders any more often than the 4x4 model-view matrix.  Since I am interested in using Metal and Direct3D render systems, doing it in the vertex shader is not going to work for me.

If I wanted to add that to my fork of Ogre, can you give me any clue on how uniforms are sent to shaders?  I don't understand about `UNPACK_MAT4` and all that.

**Comment by darksylinc** [comment]
> If I wanted to add that to my fork of Ogre, can you give me any clue on how uniforms are sent to shaders? I don't understand about UNPACK_MAT4 and all that.

I will reiterate this is a bad idea. If you need resources on that end, you can see [this entry in the FAQ](https://wiki.ogre3d.org/Ogre+2.1+FAQ#I_m_writing_my_own_Hlms_implementation_or_just_want_to_know_more_about_it._Where_do_I_find_learning_material_resources_).

As to why it's a bad idea:

 - Calculating the inverse of a 4x4 or 3x3 matrix is expensive. If it's just a few, that's a breeze. But make it for every object and it gets expensive.
 - You penalize ALL objects just for a few that need it.
    - Due to how the code is architected, it'd be very cumbersome to be able to toggle on/off at this level.
 - You need 64 bytes (48 + 16 of padding) of additional bandwidth and storage requirements, _per object._ This impacts caches and available BW.

>  Since I am interested in using Metal and Direct3D render systems, doing it in the vertex shader is not going to work for me.

I apologize, I forget not everyone realizes has what is going on in my mind: Metal & HLSL don't have `inverse()` intrinsics but you can implement it via code using [Matrix3::inverse](https://github.com/OGRECave/ogre-next/blob/0a6cd24a910aee6fe30b9c55f72e68963a8b2c03/OgreMain/src/OgreMatrix3.cpp#L184-L212) and/or [Matrix4::inverse](https://github.com/OGRECave/ogre-next/blob/0a6cd24a910aee6fe30b9c55f72e68963a8b2c03/OgreMain/src/OgreMatrix4.cpp#L103-L162) as reference.

The reason I mentioned GLSL having it as an intrinsic is because for a quick prototype it is easier and faster, since you know for certain GLSL's inverse() works and can focus on the actual algorithm.

When writing your version with HLSL/Metal you have to first make sure everything is alright (most notably row-major vs column-major and order of operands supplied to float3x3 constructors).

Note that you have helpers like [toFloat3x3 and buildMatrix3x3](https://github.com/OGRECave/ogre-next/blob/0a6cd24a910aee6fe30b9c55f72e68963a8b2c03/Samples/Media/Hlms/Common/HLSL/CrossPlatformSettings_piece_all.hlsl#L15-L16) defined in each CrossPlatformSettings_piece_all variant.

Furthermore calculating it in the vertex shader, although more expensive in terms of ALU computation, due to how Hlms works, it can be toggled dynamically without much cost for those who need it vs those who don't.

It could be made a global toggle (i.e. per pass), a material toggle (all materials using it), or even made per Renderable (i.e. only that specific object must always do correct normals).

**Comment by jwwalker** [comment]
@darksylinc I have implemented changes to `Hlms/Pbs/Any/Main/800.VertexShader_piece_vs.any` controlled by a property `accurate_non_uniform_scaled_normals`, and it's looking right with Metal, Direct3D, and Vulkan.  If I were to make a PR for this, should there be any API to control it, other than setting `accurate_non_uniform_scaled_normals` to 1 in an Hlms listener?

**Comment by darksylinc** [comment]
Now that you've merged your PR, I forgot to ask: Where do you think this toggle is best?

1. Per Item: Possible but a bit clunky to support & maintain from OgreNext side
2. Per Material: Easy
3. Global: also easy

The main benefit of being per material is that you can toggle it for some materials that will use Items that need it; without sacrificing the perf cost to everything else.

The main benefit of global is that you don't have to worry about forgetting to toggle it on for a material/Item pair that needs it.

**Comment by jwwalker** [comment]
@darksylinc Per material would not be good for me.  I have a cache of materials, and one material may be used for some items that are non-uniformly scaled and some that are not.  Per item would probably be best for me, but I don't mind it being global.

**Comment by darksylinc** [comment]
> I have a cache of materials, and one material may be used for some items that are non-uniformly scaled and some that are not

You don't have to strictly apply it to just the ones that need it.

You can toggle it on if one Item requires it, and if the other Items don't; then those Items are penalized. But other Items using other materials won't be penalized.

Does that scheme make sense?

**Comment by jwwalker** [comment]
@darksylinc Yes, I see what you mean, I could do that.

**Comment by darksylinc** [comment]
I'm back here to implement this feature and I totally forgot about your PR.

But what SERIOUSLY surprised me is that your PR implemented the **adjoint**! This technique was not widely known [until recently](https://x.com/iquilezles/status/1866219178409316362)! And I didn't even realize!

This changes things, because the adjoint is much cheaper to calculate than the inverse.

I'm still evaluating everything, but this issue is getting high priority.

**Comment by jwwalker** [comment]
I didn't know that it was an unusual technique.  The adjoint and the inverse differ by a scalar multiple, and since the resulting vector can be normalized, the scalar multiple doesn't matter.  So I seemed like a fairly natural optimization.

**Comment by darksylinc** [comment]
[Fixed](https://github.com/OGRECave/ogre-next/commit/3d68c1af09db83cabd276669a407ab99926a76b6)!

Commit https://github.com/OGRECave/ogre-next/commit/b6f12ea105205e6f624a16e12c9f5f73e2f1d701 is also relevant. Thanks for all the help!

> I didn't know that it was an unusual technique. The adjoint and the inverse differ by a scalar multiple, and since the resulting vector can be normalized, the scalar multiple doesn't matter. So I seemed like a fairly natural optimization.

I learn something new every day! The text-book solution was to apply inverse then transpose. It's interesting how you arrived to the adjugate via a different reasoning.
