### ISSUE TITLE
Miss-spelled blendWeights in VulkanMappings

### ISSUE THREAD

**Issue by stevenlgreen00** [OGRECave/ogre-next#386]
I am exploring ogre-next vulkan shader implementation, and came across a miss-spelled label.

I do not know if this really causes an issue anywhere.
```
In OgreVulkanMappings.cpp:
VertexElementSemantic VulkanMappings::getHlslSemantic( const char *sem ) {
      ...
      // I think this should be "input.blendWeights"
      if( strcmp( sem, "input.blendWeigth" ) == 0 )
            return VES_BLEND_WEIGHTS;
      ...
}
```

**Comment by darksylinc** [comment]
Thanks.

[Fixed](https://github.com/OGRECave/ogre-next/commit/550a76de7bee903f950ff30c22b719697a496085).

For reference, we support two ways of compiling to SPIR-V:

1. GLSL, via glslang (default)
2. HLSL, via glslang (not recommended)

HLSL support was an interesting attempt but ultimately it was abandoned because glslang doesn't have good support for it. It's ok for basic stuff but it had various issues when doing cross platform (e.g. Android) support or doing more advanced operations.

I'm not even sure if HLSL via glslang is enabled by default, thus this bug impacts very few people, if any. We may even remove support for HLSL via glslang due to being abandoned.

Nowadays even Khronos itself recommends to use [dxc](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst) instead of glslang to support HLSL in Vulkan. We haven't done any work on integrating dxc, and we don't have it planned either, at least for now.

The main reason for our lack of interest is that dxc's SPIR-V flavour requires some Vulkan extensions that are unavailable on some Android devices, and Android support is a big appeal for Ogre-Next's Vulkan RenderSystem.

Cheers
