### ISSUE TITLE
Compile warning in OgreVulkanRootLayout.cpp

### ISSUE THREAD

**Issue by jwwalker** [OGRECave/ogre-next#481]
#### System Information
- Ogre Version: master branch commit 2c3ee8245c
- Operating System / Platform: Windows 11
- RenderSystem: Vulkan

#### Detailed description
When building the Vulkan render system for `x86_64` using Visual Studio Community 2022, I get a couple of warnings in `VulkanRootLayout::calculateFirstDirtySet`, such as on this line:

```c++
bDirty |= table.dirtyBakedUavs & ( (int)ranges[DescBindingTypes::UavBuffer].isInUse() |
                                   (int)ranges[DescBindingTypes::UavTexture].isInUse() );
```

The warning is

```
warning C4805: '&': unsafe mix of type `const bool` and `int` in operation
```

All the variables and function results being combined in this code are of type `bool`.  I assume that the reason for using bitwise operations rather than boolean operations is that there is no `||=` operator in C++.  But I don't understand the reason for the `(int)` casts.  Without those casts, the code compiles without warning, but maybe I am missing something.  I assume this will not be a high priority item, I was just curious.

**Comment by darksylinc** [comment]
Hi!

Thanks for the report. I [pushed a fix](https://github.com/OGRECave/ogre-next/commit/3ff1183792707db382b81d2a21591acde3da5010). Let me know if that fixes it.

>  Without those casts, the code compiles without warning, but maybe I am missing something. I assume this will not be a high priority item, I was just curious.

`a | b | c | d` is not the same as `a || b || c || d` because the latter short circuits (i.e. if a is true, it skips the rest) while the former never branches and can be parallelized (e.g. a|b and c|d can be executed in parallel at instruction level).
The `||` form may not be ideal for branch prediction & speculative execution (debatable, YMMV).

But Clang & GCC were complaining about doing | on bool operators. So (int) was added.
But now MSVC is complaining we were doing & on bools and ints. Sigh.

**Comment by jwwalker** [comment]
@darksylinc  Yes, that fixes the warning for me, and thanks for the explanation.
