### ISSUE TITLE
Code does not compile with VS2019: internal compiler error

### ISSUE THREAD

**Issue by maxgolov** [OGRECave/ogre-next#64]
#### System Information
- Ogre Version: master (Dec 26 2019)
- Operating System / Platform: Windows 10 x64 
- RenderSystem: 
- GPU: Nvidia RTX2070

#### Detailled description
Latest Visual Studio 2017 (vc141) and Visual Studio 2019 latest compiler update (VisualStudio.16.Release/16.4.2+29613.14) both don't like the code that lives in:

```
OgreMain\src\OgreImageDownsampler.cpp(197,14):
fatal error C1001: An internal error has occurred in the compiler.
```

The issue has been also reported here:
https://developercommunity.visualstudio.com/content/problem/601701/ogre-v21-source-internal-compiler-error-with-visua.html

Compiler doesn't like when a .cpp module gets recursively included with different set of macro definitions. Proposed workaround is to refactor the code in _OgreImageDownsampler.cpp_ by moving the 'problematic' piece of macro-magic code (that recursively includes itself) -- into its own separate header with a different name. After that refactor all the code compiles successfully and works great.

I'm attaching a proposed .patch below

#### Ogre.log
N/A

#### Callstack
N/A

[vs2019_compiler_error.patch.txt](https://github.com/OGRECave/ogre-next/files/4044301/vs2019_compiler_error.patch.txt)

**Comment by digimatic** [comment]
We have  this problem also, as a workaround we turn off precompiled headers. The problem goes away. 

Patch:

index ae84b594e5..93b4122514 100644
--- a/OgreMain/CMakeLists.txt
+++ b/OgreMain/CMakeLists.txt
@@ -457,10 +457,12 @@ endif ()
 #set_source_files_properties("${CMAKE_CURRENT_SOURCE_DIR}/src/OgreSubMesh2.cpp" PROPERTIES HEADER_FILE_ONLY FALSE)

 # specify a precompiled header to use
-use_precompiled_header(OgreMain
-  "${CMAKE_CURRENT_SOURCE_DIR}/include/OgreStableHeaders.h"
-  "${CMAKE_CURRENT_SOURCE_DIR}/src/OgrePrecompiledHeaders.cpp"
-)
+if((NOT MSVC) AND (NOT (MSVC_VERSION EQUAL 1920))) # temporary hack because Internal compiler error compiling OgreImageDownsampler.cpp with new vs 2019
+  use_precompiled_header(OgreMain
+    "${CMAKE_CURRENT_SOURCE_DIR}/include/OgreStableHeaders.h"
+    "${CMAKE_CURRENT_SOURCE_DIR}/src/OgrePrecompiledHeaders.cpp"
+  )
+endif()

 # install OgreMain
 ogre_config_lib(OgreMain TRUE)

**Comment by TaaTT4** [comment]
Another workaround (that doesn't require to touch the source code) is to build OGRE with `OGRE_UNITY_BUILD` set to `TRUE`.
