### ISSUE TITLE
How to enable DDGI

### ISSUE THREAD

**Issue by blockspacer** [OGRECave/ogre-next#78]
Hi, 
Is it possible to test DDGI now?
What is the status of DDGI?

https://morgan3d.github.io/articles/2019-04-01-ddgi/

**Comment by darksylinc** [comment]
Hi!

Yes, we have it implemented.

The DDGI implemented in that article uses RayTracing.

We have implemented DDGI with two alternative variants: using Voxels, and using Rasterization.

To test either of them, clone the [v2-2-irradiance-field](https://github.com/OGRECave/ogre-next/tree/v2-2-irradiance-field) branch, enable OGRE_BUILD_TESTS in the CMake configuration, and run Test_Voxelizer sample.

It has many GI options. In Ogre-next, we call DDGI "IFD" (Irradiance Field with Distance), which is a more generic name since the first 'D' in DDGI stands for 'dynamic', something that is mostly possible thanks to HW raytracing.

**Comment by blockspacer** [comment]
@darksylinc thanks for answer, good news
