### ISSUE TITLE
Use relative file postioning in includes

### ISSUE THREAD

**Issue by Caellian** [OGRECave/ogre-next#92]
I'm completely new to OGRE and I've been setting up my project according to the official tutorial [here](https://ogrecave.github.io/ogre/api/latest/setup.html). I'm using Arch Linux. I know ogre-next is not very friendly for new users but I'd prefer using ogre-next for learning as it'll force me to get more familiar with how it works. I used setup scripts to setup ogre and installed it using generated ninja files.

`#include <OGRE/Ogre.h>` gives me an error [here](https://github.com/OGRECave/ogre-next/blob/6a814a02e69dfe3c006baf8ec6399aeb611452ca/OgreMain/include/Vao/OgreVertexBufferPacked.h#L32) saying that `"Vao/OgreBufferPacked.h"` file does not exist.
I checked locally, it's does (`/usr/local/include/OGRE/Vao/OgreBufferPacked.h`).

From looking at sources I infer that `OGRE` is actually the root of included files - by which I mean \#include <Ogre.h> would actually include that file in project sources. Problem is that on Linux, it is placed in `/usr/local/include/OGRE` file which means that all ogre includes have to be prefixed with `OGRE/`. Prepending `OGRE/` to header include paths fixes this issue. Moving the includes outside of 'OGRE' subdirectory would too, but I don't want to pollute my include directory with files unmanaged by the package manager.
What I also find confusing is the usage of `"` for absolute include paths. From my understanding of C++, `"` is conventionally used for relative include paths and angled brackets for paths relative to searched include directories (although `"` falls back to that behaviour so I might be just nitpicking now). Using relative include paths would be much better in cases like these and would make include files resilient to inconsistent placement.

Placing ogre headers directly inside include directory is bad.
Here are some possible solutions:
- Consider using relative paths in `#include "something.h"` statements, this would make setting up SDK much simpler.
- Consider moving includes into OGRE subdirectory (requires much larger refactoring, breaks stuff, not really an option)

While this might be easy to fix with a script prepending OGRE to includes, consider the fact that lots of new users using Linux will face a similar problem and patching files locally is not the best solution.
I might also be doing something wrong in which case most of the issue above doesn't make much sense.

**Comment by AllianceDarkSylinc** [comment]
Hi!

Beware the tutorial you're looking at is for ogre 1.x. This branch is [ogre-next](https://ogrecave.github.io/ogre-next/api/2.1/_using_ogre_in_your_app.html).
Although there are many similarities, there will also be differencies.

*The short version:*
The error you're getting can be fixed by adding '/usr/local/include/OGRE' to the include paths.

It is an historical artifact carried from Ogre 1.x where an out-of-source build does not 100% match with an SDK installation. We tried to correct this but as you said it needed a larger refactoring; particularly on our CMake scripts.

We usually discourage installing SDKs into Linux because C++ projects, unlike C, have terrible ABI compatibility and it gets worse if two projects need different build options; while encouraging the use of [EmptyProject](https://github.com/OGRECave/ogre-next/tree/6a814a02e69dfe3c006baf8ec6399aeb611452ca/Samples/2.0/Tutorials/EmptyProject) which is prepared for out of source builds (i.e. no SDK installation).

Nonetheless if you want to use SDK installations I can still help you with it, or if you want to improve the state then patches can be discussed.

**Comment by darksylinc** [comment]
Hi!

Beware the tutorial you're looking at is for ogre 1.x. This branch is [ogre-next](https://ogrecave.github.io/ogre-next/api/2.1/_using_ogre_in_your_app.html).
Although there are many similarities, there will also be differencies.

**The short version:**
The error you're getting can be fixed by adding '/usr/local/include/OGRE' to the include paths.

**The long version:**
It is an historical artifact carried from Ogre 1.x where an out-of-source build does not 100% match with an SDK installation. We tried to correct this but as you said it needed a larger refactoring; particularly on our CMake scripts.

We usually discourage installing SDKs into Linux because C++ projects, unlike C, have terrible ABI compatibility and it gets worse if two projects need different build options; while encouraging the use of [EmptyProject](https://github.com/OGRECave/ogre-next/tree/6a814a02e69dfe3c006baf8ec6399aeb611452ca/Samples/2.0/Tutorials/EmptyProject) which is prepared for out of source builds (i.e. no SDK installation).

Nonetheless if you want to use SDK installations I can still help you with it, or if you want to improve the state then patches can be discussed.

**Comment by Caellian** [comment]
> Beware the tutorial you're looking at is for ogre 1.x. This branch is [ogre-next](https://ogrecave.github.io/ogre-next/api/2.1/_using_ogre_in_your_app.html).
> Although there are many similarities, there will also be differences.

I'm expecting these issues to arise, I was using it because it has more of a step-by-step approach which should make it easier to learn stuff (although, if you know any semi-finished OSS games following "good practices", it would help even more). I expected errors down the line for which I'd look at "Changes" and "FAQ" sections of the docs. I don't expect to use too complex features as I'm basically trying to make a procedural voxel game (like Minetest).

> **The long version:**
> It is an historical artefact carried from Ogre 1.x where an out-of-source build does not 100% match with an SDK installation. We tried to correct this but as you said it needed a larger refactoring; particularly on our CMake scripts.

Is such a large refactoring even an option? I presume that a lot of people depend on non-prefixed paths. Moving the headers would mean everyone using ogre has to fix all ogre includes in their projects (although this is very trivial to do). Using relative include paths would be a much better option IMO. It would also require no changes in projects relying on current include paths.

> We usually discourage installing SDKs into Linux because C++ projects, unlike C, have terrible ABI compatibility and it gets worse if two projects need different build options; while encouraging the use of EmptyProject which is prepared for out of source builds (i.e. no SDK installation).

This makes a lot of sense and changes how I feel about installing it. Is it okay to provide the SDK as a submodule in the repo so that users don't have to manually set it up? I'm going to play around with this a little and see how it goes (primarily add_subdirectory(libs/ogre) and linking to generated targets).

> Nonetheless if you want to use SDK installations I can still help you with it, or if you want to improve the state then patches can be discussed.

As I continue along and get more familiar with the requirements and how ogre works, I might create a PR fixing this, although, as you've mentioned, different projects have different requirements.
I will try to write a python script that goes through all includes and changes their include paths from absolute to relative, see how that goes and post it here when I'm done and test it (building the ogre SDK and including OGRE/Ogre.h). I saw yesterday that some includes are in fact relative so using grep to manually patch everything likely isn't a sane way of doing this.

**Comment by Caellian** [comment]
Oh wow, it's not as trivial to change include paths to relative as I initially thought. Apart from alternative root include directories, modules (Components) complicate this a lot. Ideally, as they are not part of core, they should be using <>, but that goes back to moving all headers problem. With these problems, I do still 

Anyway, I wrote the python [script](https://gist.github.com/Caellian/0648469f6aec65f0f21b689a48480f47) I mentioned earlier. It automatically changes all absolute paths (optionally even <> paths), to relative paths. It does so in a safe way by checking whether the target file exists. It can also simulate fake files for files generated by CMake/build scripts. It might be good to apply it to at least OgreCore for now and then modules can be tackled later. Review all the changes it does, didn't have time to test it properly yet.

Linux users might also find the script useful if they insist on installing the SDK to fix their includes. They will have to manually add fake files to the `FakeFiles` list for headers which aren't in included in their environment. I'd provide mine but I decided not to install the SDK.

Also, here are some wanky includes and inconsistencies I found using the script:
- `OgreWorkarounds.h` is not UTF-8 encoded but using (I presume) Windows encoding because it was probably edited by something like Notepad.
- `WIN32/OgreConfigDialogImpWinRT.h:37` uses `#include "windows.h"` instead of `#include <windows.h>`
- `OgreIdString.h:45` uses `#include "assert.h"` instead of `#include <cassert>`
I'll create a PR for those.

**Comment by darksylinc** [comment]
Hi!

I need to go so I'll be brief.

I'm a bit confused with your understanding of include headers.

#include <file.h> means the compiler will look for the file in system headers first
#include "file.h" means the compiler will look in the local folder first

That's it.

Like I said this problem goes away by including /usr/local/include/OGRE among included directories. I fail to see why is this a problem?


> * `OgreWorkarounds.h` is not UTF-8 encoded but using (I presume) Windows encoding because it was probably edited by something like Notepad.
> 
> * `WIN32/OgreConfigDialogImpWinRT.h:37` uses `#include "windows.h"` instead of `#include <windows.h>`

These two are bugs


> `OgreIdString.h:45` uses `#include "assert.h"` instead of `#include <cassert>`

This is intentional. Ogre-next tries to adhere to some [Orthodox C++ conventions](https://gist.github.com/bkaradzic/2e39896bc7d8c34e042b)

**Comment by Caellian** [comment]
I know they only change priority but using <> implies that header is a system header/externally provided while "" the other way around. This doesn't cause any problems, it just increases clarity.

Including `/usr/local/include/OGRE` is the easiest solution. Regarding the rest, I was trying to automate the grindy part of the job in case you decide to make SDK installation work without additional include paths down the line.

Issue can be closed.
